[project]
name = "oop"
version = "0.1.0"
description = "Learning OOP in Python."
authors = [
    {name = "Carlos Pizarro",email = "pizarro.c.barboza@outlook.com"}
]
requires-python = ">=3.10"
dependencies = [
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "mypy (==2.3.1)",
    "pydantic (>=2.13.4,<3.0.0)",
    "pytest (>=9.1.1,<10.0.0)"
]

[tool.poetry]
package-mode = false

[tool.mypy]
# The python version your project targets
python_version = "3.11"
# Force mypy to check all files, even if they don't have type hints yet
check_untyped_defs = true
# Warns you if you return a value from a function typed to return None
warn_return_any = true
# Warns you if you have # type: ignore comments that are no longer needed
warn_unused_ignores = true
# Forces developers to type-hint the arguments and return types of ALL functions
disallow_untyped_defs = true
# -------------------------------------------------------------------
# THE ESCAPE HATCH (Crucial for real-world projects)
# -------------------------------------------------------------------
# Many 3rd-party libraries (like pandas or old boto3) don't have type hints.
# This prevents mypy from crashing when you import them.
[[tool.mypy.overrides]]
module = [
    # "some_legacy_library.*",
    # "another_untyped_lib.*"
]
ignore_missing_imports = true
